/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    java
    `maven-publish`
}

repositories {
    flatDir {
        dirs("lib")
    }
    mavenCentral()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }

    maven {
        url = uri("https://repository.jboss.org/nexus/content/groups/public/")
    }

    maven {
        url = uri("https://maven.jahia.org/maven2/")
    }

    maven {
        url = uri("https://repo.opennms.org/maven2/")
    }
}

sourceSets {
    main {
        java {
            srcDir("src")
        }
    }
}

dependencies {
    implementation("org.codehaus.groovy:groovy-jsr223:2.0.0")
    implementation("org.apache.santuario:xmlsec:1.4.4")
    implementation("org.apache.flex.blazeds:flex-messaging-core:4.7.3")
    implementation("org.apache.flex.blazeds:flex-messaging-common:4.7.3")
    implementation("org.samba.jcifs:jcifs:1.3.14-kohsuke-1")
    implementation("jfree:jfreechart:1.0.13")
    implementation("concurrent:concurrent:1.3.4")
    implementation("org.beanshell:bsh:2.0b4")
    implementation("bsf:bsf:2.3.0")
    implementation("javax.help:javahelp:2.0.02")
    implementation("org.ccil.cowan.tagsoup:tagsoup:1.0.1")
    implementation("commons-logging:commons-logging:1.1.1")
    implementation("org.bouncycastle:bcprov-jdk15on:1.48")
    implementation("org.bouncycastle:bcpkix-jdk15on:1.48")
    implementation("xerces:xercesImpl:2.9.1")
    implementation("xalan:xalan:2.7.1")
    implementation("joda-time:joda-time:1.6.2")
    implementation("org.openid4java:openid4java-nodeps:0.9.6")
    implementation("commons-codec:commons-codec:1.5")
    testImplementation("junit:junit:4.8.2")
    testImplementation("log4j:log4j:1.2.16")
    implementation("htmlparser:htmlparser:1.5")
    implementation("chardet:chardet:1.0")
}

group = "org.owasp.webscarab"
version = "1.0.0-SNAPSHOT"
description = "WebScarab"
java.sourceCompatibility = JavaVersion.VERSION_1_6

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}
