/*
 * BeanShellPanel.java
 *
 * Created on November 6, 2003, 7:26 AM
 */

package org.owasp.webscarab.ui.swing.editors;

import org.owasp.webscarab.model.Request;
import org.owasp.webscarab.model.Response;

import bsh.util.JConsole;
import bsh.Interpreter;

/**
 *
 * @author  rdawes
 */
public class BeanShellPanel extends javax.swing.JPanel implements ByteArrayEditor {
    
    private boolean _editable = false;
    private byte[] _data = new byte[0];
    private JConsole _console;
    private Interpreter _interpreter;
    private Request _request = null;
    private Response _response = null;
    
    /** Creates new form BeanShellPanel */
    public BeanShellPanel() {
        initComponents();
        _console = new JConsole();
        _interpreter = new Interpreter( _console );
        
        // How do we set stdout to go to the console?
        // print () works, but System.out.println() doesn't
        
        // _interpreter.setOut(_console.getOut());
        // _interpreter.setErr(_console.getErr());
        
        new Thread( _interpreter ).start(); // start a thread to call the run() method
        beanPanel.add(_console);
    }
    
    public String[] getContentTypes() {
        return new String[] { ".*" };
    }    
    
    public void setEditable(boolean editable) {
        _editable = editable;
    }
    
    public void setBytes(byte[] bytes) {
        System.err.println("Setting content");
        _data = new byte[bytes.length];
        System.arraycopy(bytes, 0, _data, 0, bytes.length);
        try {
            _interpreter.set("content", _data);
        } catch (bsh.EvalError ee) {
            System.err.println("Eval error : " + ee);
        }
    }
    
    public boolean isModified() {
        return _editable;
    }
    
    public byte[] getBytes() {
        System.err.println("Getting content");
        if (_editable) {
            try {
                _data = (byte[]) _interpreter.get("content");
            } catch (Exception e) {
                System.err.println("Error getting content from the interpreter : " + e);
            }
        }
        return _data;
    }
    
    public void setRequest(Request request) {
        if (request != null) {
            _request = new Request(request);
        } else {
            _request = null;
        }
        try {
            _interpreter.set("request", _request);
        } catch (Exception e) {
            System.err.println("Error setting Request : " + e);
        }
    }
    
    public Request getRequest() {
        if (_editable) {
            try {
                _request = (Request) _interpreter.get("request");
            } catch (Exception e) {
                System.err.println("Error getting request : " + e);
            }
        }
        return _request;
    }
    
    public void setResponse(Response response) {
        if (response != null) {
            _response = new Response(response);
        } else {
            _response = null;
        }
        try {
            _interpreter.set("response", _response);
        } catch (Exception e) {
            System.err.println("Error setting Response: " + e);
        }
    }
    
    public Response getResponse() {
        if (_editable) {
            try {
                _response = (Response) _interpreter.get("response");
            } catch (Exception e) {
                System.err.println("Error getting response : " + e);
            }
        }
        return _response;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        scriptComboBox = new javax.swing.JComboBox();
        loadButton = new javax.swing.JButton();
        beanPanel = new javax.swing.JPanel();

        setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("Load script ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        add(jLabel1, gridBagConstraints);

        scriptComboBox.setEditable(true);
        scriptComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scriptComboBoxActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        gridBagConstraints.weightx = 1.0;
        add(scriptComboBox, gridBagConstraints);

        loadButton.setText("Browse");
        loadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadButtonActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        add(loadButton, gridBagConstraints);

        beanPanel.setLayout(new java.awt.BorderLayout());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(beanPanel, gridBagConstraints);

    }//GEN-END:initComponents

    private void loadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadButtonActionPerformed
        System.out.println("loadButton pressed");
    }//GEN-LAST:event_loadButtonActionPerformed

    private void scriptComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scriptComboBoxActionPerformed
        if (evt.getActionCommand().equals("comboBoxChanged")) {
            System.err.println("Should try to load " + ((javax.swing.JComboBox)evt.getSource()).getSelectedItem());
        } else if (evt.getActionCommand().equals("comboBoxEdited")) {
            System.err.println("Should add " + ((javax.swing.JComboBox)evt.getSource()).getSelectedItem() + " to the history");
        }
    }//GEN-LAST:event_scriptComboBoxActionPerformed

    public static void main(String[] args) {
        byte[] content = new byte[0];
        try {
            java.io.ByteArrayOutputStream baos = new java.io.ByteArrayOutputStream();
            // FileInputStream fis = new FileInputStream("/usr/share/xfce/backdrops/Flower.jpg");
            java.io.FileInputStream fis = new java.io.FileInputStream("/home/rdawes/exodus/HowTo.html");
            byte[] buff = new byte[1024];
            int got = 0;
            while ((got = fis.read(buff)) > 0) {
                baos.write(buff, 0, got);
            }
            content = baos.toByteArray();
        } catch (Exception e) {
            System.exit(0);
        }
        
        javax.swing.JFrame top = new javax.swing.JFrame("BeanShell Pane");
        top.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                System.exit(0);
            }
        });
        
        BeanShellPanel bsp = new BeanShellPanel();
        top.getContentPane().add(bsp);
        top.setBounds(100,100,600,400);
        top.show();
        try {
            bsp.setEditable(true);
            bsp.setBytes(content);
            Thread.currentThread().sleep(20000);
            content = bsp.getBytes();
            System.err.println("content length : " + content.length);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel beanPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton loadButton;
    private javax.swing.JComboBox scriptComboBox;
    // End of variables declaration//GEN-END:variables
    
}
