/*
 * ConversationPanel.java
 *
 * Created on November 7, 2003, 10:56 AM
 */

package org.owasp.webscarab.ui.swing;

import javax.swing.JFrame;
import org.owasp.webscarab.model.Request;
import org.owasp.webscarab.model.Response;

import javax.swing.border.TitledBorder;
import java.awt.Dimension;
import java.awt.Point;

/**
 *
 * @author  rdawes
 */
public class ConversationPanel extends javax.swing.JPanel {
    
    private RequestPanel _requestPanel;
    private ResponsePanel _responsePanel;
    private JFrame _frame = null;
    
    private static Dimension _size = null;
    private static Point _location = null;
    
    /** Creates new form ConversationPanel */
    public ConversationPanel() {
        initComponents();
        
        _requestPanel = new RequestPanel();
        _requestPanel.setBorder(new TitledBorder("Request"));
        _responsePanel = new ResponsePanel();
        _responsePanel.setBorder(new TitledBorder("Response"));
        conversationSplitPane.setTopComponent(_requestPanel);
        conversationSplitPane.setBottomComponent(_responsePanel);
    }
    
    public void setRequest(Request request, boolean editable) {
        _requestPanel.setRequest(request, editable);
    }
    
    public Request getRequest() {
        return _requestPanel.getRequest();
    }
    
    public void setResponse(Response response, boolean editable) {
        _responsePanel.setResponse(response, editable);
    }
    
    public Response getResponse() {
        return _responsePanel.getResponse();
    }
    
    public JFrame inFrame() {
        return inFrame("Conversation Panel");
    }
    
    public JFrame inFrame(String title) {
        if (_frame != null) {
            return _frame;
        }
        _frame = new JFrame(title);
        _frame.getContentPane().setLayout(new java.awt.BorderLayout());
        if (_size != null) {
            _frame.setSize(_size);
        } else {
            _frame.setSize(800, 600);
        }
        if (_location != null) _frame.setLocation(_location);
        _frame.getContentPane().add(this);
        _frame.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentMoved(java.awt.event.ComponentEvent evt) {
                formComponentMoved(evt);
            }
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });
        return _frame;
    }
    
    private void formComponentResized(java.awt.event.ComponentEvent evt) {
        if (! isShowing()) return;
        _size = getSize();
    }

    private void formComponentMoved(java.awt.event.ComponentEvent evt) {
        if (! isShowing()) return;
        _location = getLocation();
    }

    public JFrame getFrame() {
        return _frame;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        java.awt.GridBagConstraints gridBagConstraints;

        conversationSplitPane = new javax.swing.JSplitPane();

        setLayout(new java.awt.GridBagLayout());

        conversationSplitPane.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        conversationSplitPane.setResizeWeight(0.3);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(conversationSplitPane, gridBagConstraints);

    }//GEN-END:initComponents
    
    public static void main(String[] args) {
        Request request = new Request();
        Response response = new Response();
        try {
            String req = "c:/temp/reverse/conversations/1-request";
            String resp = "c:/temp/reverse/conversations/1-response";
            if (args.length == 2) {
                req = args[0] + "/conversations/" + args[1] + "-request";
                resp = args[0] + "/conversations/" + args[1] + "-response";
            }
            java.io.FileInputStream fis = new java.io.FileInputStream(req);
            request.read(fis);
            fis = new java.io.FileInputStream(resp);
            response.read(fis);
        } catch (Exception e) {
            e.printStackTrace();
            System.exit(0);
        }
        
        final ConversationPanel cp = new ConversationPanel();
        cp.setRequest(request, false);
        cp.setResponse(response, false);

        JFrame top = cp.inFrame();
        top.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                System.exit(0);
            }
        });
        
        javax.swing.JButton button = new javax.swing.JButton("GET");
        top.getContentPane().add(button, java.awt.BorderLayout.SOUTH);
        button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                System.out.println(cp.getRequest());
                System.out.println(cp.getResponse());
            }
        });
        top.show();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSplitPane conversationSplitPane;
    // End of variables declaration//GEN-END:variables
    
}
