/*
 * ProxyConfig.java
 *
 * Created on August 28, 2003, 9:30 PM
 */

package org.owasp.webscarab.ui.swing;

import java.awt.event.WindowEvent;
import java.util.Properties;

/**
 *
 * @author  rdawes
 */
public class ProxyConfig extends javax.swing.JDialog {
    
    private Properties _props;
    
    /** Creates new form ProxyConfig */
    public ProxyConfig(java.awt.Frame parent, boolean modal, Properties props) {
        super(parent, modal);
        _props = props;
        initComponents();
        
        String prop = "WebScarab.httpProxy";
        String value = props.getProperty(prop);
        if (value == null) value = "";
        String[] httpProxy = value.split(":");
        httpProxyServerTextField.setText(httpProxy.length == 2 ? httpProxy[0] : "");
        httpProxyPortTextField.setText(httpProxy.length == 2 ? httpProxy[1] : "");
        
        prop = "WebScarab.httpsProxy";
        value = props.getProperty(prop);
        if (value == null) value = "";
        String[] httpsProxy = value.split(":");
        httpsProxyServerTextField.setText(httpsProxy.length == 2 ? httpsProxy[0] : "");
        httpsProxyPortTextField.setText(httpsProxy.length == 2 ? httpsProxy[1] : "");
        
        prop = "WebScarab.noProxy";
        value = props.getProperty(prop);
        if (value == null) value = "";
        noProxyTextArea.setText(value);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel2 = new javax.swing.JLabel();
        httpProxyServerTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        httpProxyPortTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        httpsProxyServerTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        httpsProxyPortTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        noProxyTextArea = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        cancelButton = new javax.swing.JButton();
        applyButton = new javax.swing.JButton();

        getContentPane().setLayout(new java.awt.GridBagLayout());

        setTitle("Config proxies");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jLabel2.setText("HTTP  Proxy : ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 4, 0, 4);
        getContentPane().add(jLabel2, gridBagConstraints);

        httpProxyServerTextField.setMinimumSize(new java.awt.Dimension(150, 20));
        httpProxyServerTextField.setPreferredSize(new java.awt.Dimension(150, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        getContentPane().add(httpProxyServerTextField, gridBagConstraints);

        jLabel5.setText("Port :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 4, 0, 4);
        getContentPane().add(jLabel5, gridBagConstraints);

        httpProxyPortTextField.setMinimumSize(new java.awt.Dimension(60, 20));
        httpProxyPortTextField.setPreferredSize(new java.awt.Dimension(60, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(httpProxyPortTextField, gridBagConstraints);

        jLabel4.setText("HTTPS Proxy : ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 4, 0, 4);
        getContentPane().add(jLabel4, gridBagConstraints);

        httpsProxyServerTextField.setMinimumSize(new java.awt.Dimension(150, 20));
        httpsProxyServerTextField.setPreferredSize(new java.awt.Dimension(150, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        getContentPane().add(httpsProxyServerTextField, gridBagConstraints);

        jLabel3.setText("Port :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 4, 0, 4);
        getContentPane().add(jLabel3, gridBagConstraints);

        httpsProxyPortTextField.setMinimumSize(new java.awt.Dimension(60, 20));
        httpsProxyPortTextField.setPreferredSize(new java.awt.Dimension(60, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(httpsProxyPortTextField, gridBagConstraints);

        jLabel1.setText("No Proxy : ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 4, 0, 4);
        getContentPane().add(jLabel1, gridBagConstraints);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setMinimumSize(new java.awt.Dimension(100, 48));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(103, 51));
        noProxyTextArea.setLineWrap(true);
        noProxyTextArea.setToolTipText("Enter a comma separated list of hosts that do not need to go through the proxy");
        noProxyTextArea.setPreferredSize(null);
        jScrollPane1.setViewportView(noProxyTextArea);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(jScrollPane1, gridBagConstraints);

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        jPanel1.add(cancelButton);

        applyButton.setText("Apply");
        applyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                applyButtonActionPerformed(evt);
            }
        });

        jPanel1.add(applyButton);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        getContentPane().add(jPanel1, gridBagConstraints);

        pack();
        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setSize(new java.awt.Dimension(400, 120));
        setLocation((screenSize.width-400)/2,(screenSize.height-120)/2);
    }//GEN-END:initComponents
    
    private void applyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_applyButtonActionPerformed
        String prop;
        String value;
        try {
            String server = httpProxyServerTextField.getText().trim();
            String port = httpProxyPortTextField.getText().trim();
            value = server + ":" + port;
            prop = "WebScarab.httpProxy";
            if (!server.equals("") && !port.equals("")) {
                int p = Integer.parseInt(port);
                if (!value.equals(_props.getProperty(prop))) {
                    _props.setProperty(prop,value);
                }
            } else if (port.equals("") && !server.equals("")) {
                System.err.println("The http Proxy port must also be provided");
                return;
            } else if (server.equals("") && !port.equals("")) {
                System.err.println("The http Proxy server must also be provided");
                return;
            } else {
                if (!_props.getProperty(prop).equals("")) {
                    _props.setProperty(prop, "");
                }
            }
        } catch (NumberFormatException nfe) {
            System.err.println("Error parsing the upstream HTTP Proxy port");
            return;
        }
        
        try {
            String server = httpsProxyServerTextField.getText().trim();
            String port = httpsProxyPortTextField.getText().trim();
            value = server + ":" + port;
            prop = "WebScarab.httpsProxy";
            if (!server.equals("") && !port.equals("")) {
                int p = Integer.parseInt(port);
                if (!value.equals(_props.getProperty(prop))) {
                    _props.setProperty(prop,value);
                }
            } else if (port.equals("") && !server.equals("")) {
                System.err.println("The https Proxy port must also be provided");
                return;
            } else if (server.equals("") && !port.equals("")) {
                System.err.println("The https Proxy server must also be provided");
                return;
            } else {
                if (!_props.getProperty(prop).equals("")) {
                    _props.setProperty(prop, "");
                }
            }
        } catch (NumberFormatException nfe) {
            System.err.println("Error parsing the upstream HTTPS Proxy port");
            return;
        }
        
        value = noProxyTextArea.getText();
        prop = "WebScarab.noProxy";
        if (!value.equals(_props.getProperty(prop))) {
            _props.setProperty(prop,value);
        }
        
        this.closeDialog(new WindowEvent(this,WindowEvent.WINDOW_CLOSED));
    }//GEN-LAST:event_applyButtonActionPerformed
    
    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        this.closeDialog(new WindowEvent(this,WindowEvent.WINDOW_CLOSED));
    }//GEN-LAST:event_cancelButtonActionPerformed
    
    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField httpsProxyServerTextField;
    private javax.swing.JTextField httpsProxyPortTextField;
    private javax.swing.JButton cancelButton;
    private javax.swing.JTextField httpProxyPortTextField;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton applyButton;
    private javax.swing.JTextArea noProxyTextArea;
    private javax.swing.JTextField httpProxyServerTextField;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
    
}
