/*
 * ProxyConfig.java
 *
 * Created on August 28, 2003, 9:30 PM
 */

package org.owasp.webscarab.ui.swing;

import java.awt.event.WindowEvent;

import org.owasp.webscarab.plugin.Framework;
import org.owasp.webscarab.httpclient.HTTPClientFactory;

import org.owasp.webscarab.model.Preferences;
import java.util.Properties;

import java.util.logging.Logger;

import javax.swing.JOptionPane;

/**
 *
 * @author  rdawes
 */
public class ProxyConfig extends javax.swing.JDialog {
    
    private HTTPClientFactory _factory = HTTPClientFactory.getInstance();
    private Framework _framework;
    
    private Properties _props = Preferences.getPreferences();
    
    private Logger _logger = Logger.getLogger(getClass().getName());
    
    /** Creates new form ProxyConfig */
    public ProxyConfig(java.awt.Frame parent, Framework framework) {
        super(parent, true);
        _framework = framework;
        initComponents();
        
        httpProxyServerTextField.setText(_factory.getHttpProxy());
        httpProxyPortTextField.setText(Integer.toString(_factory.getHttpProxyPort()));
        
        httpsProxyServerTextField.setText(_factory.getHttpsProxy());
        httpsProxyPortTextField.setText(Integer.toString(_factory.getHttpsProxyPort()));
        
        String[] noproxies = _factory.getNoProxy();
        if (noproxies.length>0) {
            StringBuffer buff = new StringBuffer();
            buff.append(noproxies[0]);
            for (int i=1; i<noproxies.length;i++) {
                buff.append(", ").append(noproxies[i]);
            }
            noProxyTextArea.setText(buff.toString());
        } else {
            noProxyTextArea.setText("");
        }
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel2 = new javax.swing.JLabel();
        httpProxyServerTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        httpProxyPortTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        httpsProxyServerTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        httpsProxyPortTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        noProxyTextArea = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        applyButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        getContentPane().setLayout(new java.awt.GridBagLayout());

        setTitle("Config proxies");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jLabel2.setText("HTTP  Proxy : ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 4, 0, 4);
        getContentPane().add(jLabel2, gridBagConstraints);

        httpProxyServerTextField.setMinimumSize(new java.awt.Dimension(150, 20));
        httpProxyServerTextField.setPreferredSize(new java.awt.Dimension(150, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        getContentPane().add(httpProxyServerTextField, gridBagConstraints);

        jLabel5.setText("Port :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 4, 0, 4);
        getContentPane().add(jLabel5, gridBagConstraints);

        httpProxyPortTextField.setMinimumSize(new java.awt.Dimension(60, 20));
        httpProxyPortTextField.setPreferredSize(new java.awt.Dimension(60, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(httpProxyPortTextField, gridBagConstraints);

        jLabel4.setText("HTTPS Proxy : ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 4, 0, 4);
        getContentPane().add(jLabel4, gridBagConstraints);

        httpsProxyServerTextField.setMinimumSize(new java.awt.Dimension(150, 20));
        httpsProxyServerTextField.setPreferredSize(new java.awt.Dimension(150, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        getContentPane().add(httpsProxyServerTextField, gridBagConstraints);

        jLabel3.setText("Port :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 4, 0, 4);
        getContentPane().add(jLabel3, gridBagConstraints);

        httpsProxyPortTextField.setMinimumSize(new java.awt.Dimension(60, 20));
        httpsProxyPortTextField.setPreferredSize(new java.awt.Dimension(60, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(httpsProxyPortTextField, gridBagConstraints);

        jLabel1.setText("No Proxy : ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 4, 0, 4);
        getContentPane().add(jLabel1, gridBagConstraints);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setMinimumSize(new java.awt.Dimension(100, 48));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(103, 51));
        noProxyTextArea.setLineWrap(true);
        noProxyTextArea.setToolTipText("Enter a comma separated list of hosts that do not need to go through the proxy");
        noProxyTextArea.setPreferredSize(null);
        jScrollPane1.setViewportView(noProxyTextArea);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(jScrollPane1, gridBagConstraints);

        applyButton.setText("Apply");
        applyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                applyButtonActionPerformed(evt);
            }
        });

        jPanel1.add(applyButton);

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        jPanel1.add(cancelButton);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        getContentPane().add(jPanel1, gridBagConstraints);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-400)/2, (screenSize.height-120)/2, 400, 120);
    }//GEN-END:initComponents
    
    private void applyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_applyButtonActionPerformed
        String httpserver = httpProxyServerTextField.getText().trim();
        int httpport = -1;
        try {
            String p = httpProxyPortTextField.getText().trim();
            if (!p.equals("")) 
                httpport = Integer.parseInt(p);
            // FIXME check that the port is acceptable (1..65535)
        } catch (NumberFormatException nfe) {
            _logger.severe("Error parsing the upstream HTTP Proxy port");
            return;
        }
        
        String httpsserver = httpsProxyServerTextField.getText().trim();
        int httpsport = -1;
        try {
            String p = httpsProxyPortTextField.getText().trim();
            if (!p.equals(""))
                httpsport = Integer.parseInt(p);
            // FIXME check that the port is acceptable (1..65535)
        } catch (NumberFormatException nfe) {
            _logger.severe("Error parsing the upstream HTTPS Proxy port");
            return;
        }
        
        String[] noproxies = noProxyTextArea.getText().trim().split(" *, *");
        
        boolean running = _framework.isRunning();
        if (running) {
            if (_framework.isBusy()) {
                String[] status = _framework.getStatus();
                JOptionPane.showMessageDialog(this, status, "Error - plugins are busy", JOptionPane.ERROR_MESSAGE);
                return;
            }
            _framework.stopPlugins();
        }
        _factory.setHttpProxy(httpserver, httpport);
        _factory.setHttpsProxy(httpsserver, httpsport);
        _factory.setNoProxy(noproxies);
        if (running) {
            _framework.startPlugins();
        }
        
        _props.setProperty("WebScarab.httpProxy", httpserver+":"+httpport);
        _props.setProperty("WebScarab.httpsProxy", httpsserver+":"+httpsport);
        _props.setProperty("WebScarab.noProxy", noProxyTextArea.getText());
        
        this.closeDialog(new WindowEvent(this,WindowEvent.WINDOW_CLOSED));
    }//GEN-LAST:event_applyButtonActionPerformed
    
    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        this.closeDialog(new WindowEvent(this,WindowEvent.WINDOW_CLOSED));
    }//GEN-LAST:event_cancelButtonActionPerformed
    
    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton applyButton;
    private javax.swing.JButton cancelButton;
    private javax.swing.JTextField httpProxyPortTextField;
    private javax.swing.JTextField httpProxyServerTextField;
    private javax.swing.JTextField httpsProxyPortTextField;
    private javax.swing.JTextField httpsProxyServerTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea noProxyTextArea;
    // End of variables declaration//GEN-END:variables
    
}
