/*
 * URLTreePanel.java
 *
 * Created on September 1, 2003, 10:25 PM
 */

package org.owasp.webscarab.ui.swing;

import org.owasp.webscarab.ui.Framework;
import org.owasp.webscarab.model.URLTreeModel;
// import org.owasp.webscarab.model.URLTreeNode;

import javax.swing.tree.TreeModel;
import javax.swing.tree.TreeSelectionModel;
import javax.swing.event.TreeSelectionListener;
import javax.swing.event.TreeSelectionEvent;

/**
 *
 * @author  rdawes
 */
public class URLTreePanel extends javax.swing.JPanel implements SwingPlugin {
    
    Framework _framework;
    TreeModel _urlTreeModel;
    
    /** Creates new form URLTreePanel */
    public URLTreePanel(Framework framework) {
        _framework = framework;
        _urlTreeModel = framework.getSiteModel().getURLTreeModel();
        initComponents();
        urlTree.getSelectionModel().setSelectionMode(TreeSelectionModel.SINGLE_TREE_SELECTION);
        urlTree.setRootVisible(false);
        urlTree.setShowsRootHandles(true);

        // Listen for when the selection changes.
        urlTree.addTreeSelectionListener(new TreeSelectionListener() {
            public void valueChanged(TreeSelectionEvent e) {
                URLTreeModel.URLNode node = (URLTreeModel.URLNode) urlTree.getLastSelectedPathComponent();
                // Object node = urlTree.getLastSelectedPathComponent();
                if (node == null) return;
                // System.out.println("Selected " + node.getURL());
                // We can do something like display the entries in the URLInfo. Ideally, we should 
                // have this as part of an JTreeTable, but the license worries me :-(
            }
        });
        
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jScrollPane1 = new javax.swing.JScrollPane();
        urlTree = new javax.swing.JTree();

        setLayout(new java.awt.BorderLayout());

        urlTree.setModel(_urlTreeModel);
        jScrollPane1.setViewportView(urlTree);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);

    }//GEN-END:initComponents

    public javax.swing.JPanel getPanel() {
        return this;
    }    
    
    public String getPluginName() {
        return new String("Tree");
    }    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTree urlTree;
    // End of variables declaration//GEN-END:variables
    
}
