/*
 * SessionIDPanel.java
 *
 * Created on 16 November 2003, 08:21
 */

package org.owasp.webscarab.ui.swing.sessionid;

import org.owasp.webscarab.model.Request;
import org.owasp.webscarab.model.Response;

import org.owasp.webscarab.ui.swing.SwingPlugin;
import org.owasp.webscarab.ui.swing.SwingWorker;
import org.owasp.webscarab.ui.swing.ListComboBoxModel;
import org.owasp.webscarab.ui.swing.editors.TextPanel;
import org.owasp.webscarab.ui.swing.ResponsePanel;

import org.owasp.webscarab.plugin.sessionid.SessionIDAnalysis;
import org.owasp.webscarab.plugin.sessionid.SessionID;

import java.io.IOException;
import java.io.ByteArrayInputStream;

import javax.swing.ListModel;
import javax.swing.SwingUtilities;
import javax.swing.event.ListDataEvent;
import javax.swing.event.ListDataListener;
import javax.swing.table.TableModel;
import javax.swing.event.ChangeListener;
import javax.swing.event.ChangeEvent;

import java.util.TreeMap;

import org.jfree.chart.JFreeChart;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.XYDataset;
import org.jfree.chart.axis.ValueAxis;
import org.jfree.chart.axis.DateAxis;
import org.jfree.chart.axis.NumberAxis;
import org.jfree.chart.plot.XYPlot;
import org.jfree.chart.renderer.StandardXYItemRenderer;

/**
 *
 * @author  rdawes
 */
public class SessionIDPanel extends javax.swing.JPanel implements SwingPlugin, ListDataListener {
    
    TextPanel _requestTextPanel;
    ResponsePanel _responsePanel;
    JFreeChart _chart = null;
    
    SessionIDAnalysis _sa;
    TreeMap _idTableCache = new TreeMap();
    TreeMap _idDatasetCache = new TreeMap();
    
    /** Creates new form SessionIDPanel */
    public SessionIDPanel(SessionIDAnalysis sa) {
        _sa = sa;
        initComponents();
        
        mainTabbedPane.getModel().addChangeListener(new ChangeListener() {
            public void stateChanged(ChangeEvent e) {
                int selected = mainTabbedPane.getSelectedIndex();
                if(mainTabbedPane.getTitleAt(selected).equals("Visualisation")) {
                    String name = (String) nameComboBox.getSelectedItem();
                    if (_chart == null) {
                        _chart = createChart(null);
                        visualisationPanel.add(new ChartPanel(_chart));
                    }
                    if (name == null) {
                        return;
                    }
                    SessionIDDataset sidd = (SessionIDDataset) _idDatasetCache.get(name);
                    if (sidd == null) {
                        ListModel lm = _sa.getSessionIDList(name);
                        sidd = new SessionIDDataset(lm);
                        _idDatasetCache.put(name, sidd);
                    }
                    _chart.getXYPlot().setDataset(sidd);
                } else {
                    if (_chart != null) {
                        _chart.getXYPlot().setDataset(null);
                    }
                }
            }
        });
        _requestTextPanel = new TextPanel();
        _requestTextPanel.setEditable(true);
        _requestTextPanel.setBorder(new javax.swing.border.TitledBorder("Request"));
        _requestTextPanel.setBytes("GET http://localhost:8080/index.jsp HTTP/1.0".getBytes());
        
        _responsePanel = new ResponsePanel();
        _responsePanel.setBorder(new javax.swing.border.TitledBorder("Response"));
        _responsePanel.setEditable(false);
        
        conversationSplitPane.setTopComponent(_requestTextPanel);
        conversationSplitPane.setBottomComponent(_responsePanel);
        nameComboBox.setModel(new ListComboBoxModel(_sa.getSessionIDNames()));
        idTable.setModel(new IDTableModel(null));
        
    }
    
    private JFreeChart createChart(XYDataset data) {
        ValueAxis timeAxis = new DateAxis("Date/Time");
        timeAxis.setLowerMargin(0.02);  // reduce the default margins on the time axis
        timeAxis.setUpperMargin(0.02);
        NumberAxis valueAxis = new NumberAxis("Value");
        valueAxis.setAutoRangeIncludesZero(false);  // override default
        XYPlot plot = new XYPlot(data, timeAxis, valueAxis, null);
        plot.setRenderer(new StandardXYItemRenderer(StandardXYItemRenderer.SHAPES, null, null));
        JFreeChart chart = new JFreeChart("Title", JFreeChart.DEFAULT_TITLE_FONT, plot, false);
        return chart;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        java.awt.GridBagConstraints gridBagConstraints;

        locationButtonGroup = new javax.swing.ButtonGroup();
        mainTabbedPane = new javax.swing.JTabbedPane();
        collectionPanel = new javax.swing.JPanel();
        specPanel = new javax.swing.JPanel();
        cookieRadioButton = new javax.swing.JRadioButton();
        bodyRadioButton = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        regexTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        conversationPanel = new javax.swing.JPanel();
        conversationSplitPane = new javax.swing.JSplitPane();
        actionPanel = new javax.swing.JPanel();
        testButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        sampleSpinner = new javax.swing.JSpinner();
        fetchButton = new javax.swing.JButton();
        resultPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        dateTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        valueTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        analysisPanel = new javax.swing.JPanel();
        nameComboBox = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        idTable = new javax.swing.JTable();
        calculateButton = new javax.swing.JButton();
        visualisationPanel = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        collectionPanel.setLayout(new java.awt.GridBagLayout());

        specPanel.setLayout(new java.awt.GridBagLayout());

        cookieRadioButton.setSelected(true);
        cookieRadioButton.setText("Cookie");
        locationButtonGroup.add(cookieRadioButton);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        specPanel.add(cookieRadioButton, gridBagConstraints);

        bodyRadioButton.setText("Body");
        locationButtonGroup.add(bodyRadioButton);
        bodyRadioButton.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        specPanel.add(bodyRadioButton, gridBagConstraints);

        jLabel1.setText("Name");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        specPanel.add(jLabel1, gridBagConstraints);

        nameTextField.setText("localhost/ JSESSIONID");
        nameTextField.setToolTipText("use 'host.domain/path name' for cookies");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        specPanel.add(nameTextField, gridBagConstraints);

        jLabel2.setText("Regex");
        jLabel2.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        specPanel.add(jLabel2, gridBagConstraints);

        regexTextField.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        specPanel.add(regexTextField, gridBagConstraints);

        jLabel6.setText("Session ID Location");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        specPanel.add(jLabel6, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        collectionPanel.add(specPanel, gridBagConstraints);

        conversationPanel.setLayout(new java.awt.BorderLayout());

        conversationSplitPane.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        conversationSplitPane.setResizeWeight(0.5);
        conversationPanel.add(conversationSplitPane, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        collectionPanel.add(conversationPanel, gridBagConstraints);

        testButton.setText("Test");
        testButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testButtonActionPerformed(evt);
            }
        });

        actionPanel.add(testButton);

        jLabel3.setText("Samples");
        actionPanel.add(jLabel3);

        sampleSpinner.setMinimumSize(new java.awt.Dimension(61, 24));
        sampleSpinner.setPreferredSize(new java.awt.Dimension(61, 24));
        actionPanel.add(sampleSpinner);

        fetchButton.setText("Fetch");
        fetchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fetchButtonActionPerformed(evt);
            }
        });

        actionPanel.add(fetchButton);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        collectionPanel.add(actionPanel, gridBagConstraints);

        resultPanel.setLayout(new java.awt.GridBagLayout());

        jLabel4.setText("Date");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        resultPanel.add(jLabel4, gridBagConstraints);

        dateTextField.setEditable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        resultPanel.add(dateTextField, gridBagConstraints);

        jLabel5.setText("Value");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        resultPanel.add(jLabel5, gridBagConstraints);

        valueTextField.setEditable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        resultPanel.add(valueTextField, gridBagConstraints);

        jLabel7.setText("Results");
        resultPanel.add(jLabel7, new java.awt.GridBagConstraints());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        collectionPanel.add(resultPanel, gridBagConstraints);

        mainTabbedPane.addTab("Collection", collectionPanel);

        analysisPanel.setLayout(new java.awt.GridBagLayout());

        nameComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameComboBoxActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        analysisPanel.add(nameComboBox, gridBagConstraints);

        jLabel8.setText("Session Identifier");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        analysisPanel.add(jLabel8, gridBagConstraints);

        idTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(idTable);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        analysisPanel.add(jScrollPane1, gridBagConstraints);

        calculateButton.setText("Calculate");
        calculateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateButtonActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        analysisPanel.add(calculateButton, gridBagConstraints);

        mainTabbedPane.addTab("Analysis", analysisPanel);

        mainTabbedPane.addTab("Visualisation", visualisationPanel);

        add(mainTabbedPane, java.awt.BorderLayout.CENTER);

    }//GEN-END:initComponents
    
    private void nameComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameComboBoxActionPerformed
        String name = (String)nameComboBox.getSelectedItem();
        TableModel tm = (TableModel) _idTableCache.get(name);
        if (tm == null) {
            tm = new IDTableModel(_sa.getSessionIDList(name));
            _idTableCache.put(name, tm);
        }
        idTable.setModel(tm);
    }//GEN-LAST:event_nameComboBoxActionPerformed
    
    private void calculateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateButtonActionPerformed
        String name = (String)nameComboBox.getSelectedItem();
        if (name != null && !name.equals("")) {
            _sa.calculate(name);
        }
    }//GEN-LAST:event_calculateButtonActionPerformed
    
    private void fetchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fetchButtonActionPerformed
        Request request = parseRequestPanel();
        if (request == null) {
            System.err.println("Request was null");
            return;
        }
        int location = -1;
        if (cookieRadioButton.isSelected()) {
            location = _sa.LOCATION_COOKIE;
        } else if (bodyRadioButton.isSelected()) {
            location = _sa.LOCATION_BODY;
        } else {
            System.err.println("invalid location");
            return;
        }
        int count = ((Integer)sampleSpinner.getValue()).intValue();
        System.out.println("Count = " + count);
        ListModel listModel = _sa.getSessionIDs(request, location, nameTextField.getText(), regexTextField.getText(), count);
        listModel.addListDataListener(this);
    }//GEN-LAST:event_fetchButtonActionPerformed
    
    private void testButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_testButtonActionPerformed
        final Request request = parseRequestPanel();
        if (request == null) {
            return;
        }
        final int location;
        if (cookieRadioButton.isSelected()) {
            location = _sa.LOCATION_COOKIE;
        } else if (bodyRadioButton.isSelected()) {
            location = _sa.LOCATION_BODY;
        } else {
            location = -1;
        }
        Response response = _sa.fetchResponse(request);
        if (response == null) {
            return;
        }
        new SwingWorker() {
            public Object construct() {
                return _sa.fetchResponse(request);
            }
            
            //Runs on the event-dispatching thread.
            public void finished() {
                Response response = (Response) getValue();
                if (response != null) {
                    _responsePanel.setResponse(response);
                    SessionID sessid = _sa.getIDfromResponse(response, location, nameTextField.getText(), regexTextField.getText());
                    if (sessid != null) {
                        dateTextField.setText(sessid.getDate().toString());
                        valueTextField.setText(sessid.getValue());
                    }
                }
            }
        }.start();
    }//GEN-LAST:event_testButtonActionPerformed
    
    private Request parseRequestPanel() {
        try {
            ByteArrayInputStream bais = new ByteArrayInputStream(_requestTextPanel.getBytes());
            Request request = new Request();
            request.read(bais);
            if (request.getVersion() != null) {
                return request;
            }
        } catch (IOException ioe) {
        }
        return null;
    }
    
    public javax.swing.JPanel getPanel() {
        return this;
    }
    
    public String getPluginName() {
        return "SessionID Analysis";
    }
    
    public static void main(String[] args) {
        javax.swing.JFrame top = new javax.swing.JFrame("SessionID Analysis");
        top.getContentPane().setLayout(new java.awt.BorderLayout());
        top.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                System.exit(0);
            }
        });
        javax.swing.JButton button = new javax.swing.JButton("GET");
        SessionIDPanel sp = new SessionIDPanel(new SessionIDAnalysis(null));
        top.getContentPane().add(sp);
        top.setBounds(100,100,800,600);
        top.show();
    }
    
    public void contentsChanged(ListDataEvent e) {
    }
    
    public void intervalAdded(ListDataEvent e) {
        ListModel lm = (ListModel) e.getSource();
        final SessionID id = (SessionID) lm.getElementAt(lm.getSize()-1);
        SwingUtilities.invokeLater(new Runnable() {
            public void run() {
                dateTextField.setText(id.getDate().toString());
                valueTextField.setText(id.getValue());
            }
        });
    }
    
    /** Sent after the indices in the index0,index1 interval
     * have been removed from the data model.  The interval
     * includes both index0 and index1.
     *
     * @param e  a <code>ListDataEvent</code> encapsulating the
     *    event information
     *
     */
    public void intervalRemoved(ListDataEvent e) {
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField regexTextField;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel actionPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField dateTextField;
    private javax.swing.JPanel visualisationPanel;
    private javax.swing.JTable idTable;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel analysisPanel;
    private javax.swing.JButton fetchButton;
    private javax.swing.JButton testButton;
    private javax.swing.JRadioButton bodyRadioButton;
    private javax.swing.JComboBox nameComboBox;
    private javax.swing.ButtonGroup locationButtonGroup;
    private javax.swing.JPanel conversationPanel;
    private javax.swing.JPanel resultPanel;
    private javax.swing.JSpinner sampleSpinner;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JRadioButton cookieRadioButton;
    private javax.swing.JSplitPane conversationSplitPane;
    private javax.swing.JButton calculateButton;
    private javax.swing.JTextField valueTextField;
    private javax.swing.JPanel collectionPanel;
    private javax.swing.JTabbedPane mainTabbedPane;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JPanel specPanel;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
    
}
