/*
 * ProxyPanel.java
 *
 * Created on July 25, 2003, 11:07 PM
 */

package org.owasp.webscarab.ui.swing.proxy;

import org.owasp.webscarab.ui.swing.SwingPlugin;
import org.owasp.webscarab.plugin.proxy.Proxy;
import org.owasp.webscarab.plugin.proxy.module.*;

import java.util.ArrayList;

/**
 *
 * @author  rdawes
 */
public class ProxyPanel extends javax.swing.JPanel implements SwingPlugin {
    
    private Proxy _proxy;

    private ArrayList _plugins;
    private SwingPlugin[] _pluginArray = new SwingPlugin[0];
    
    /** Creates new form ProxyPanel */
    public ProxyPanel(Proxy proxy) {
        _proxy = proxy;
        initComponents();
        configure();
        ManualEdit me = new ManualEdit();
        proxy.addPlugin(me);
        RevealHidden rh = new RevealHidden();
        proxy.addPlugin(rh);
        
        addPlugin(new ManualEditPanel(me));
        addPlugin(new RevealHiddenPanel(rh));
    }

    public javax.swing.JPanel getPanel() {
        return this;
    }
    
    public String getPluginName() {
        return new String("Proxy");
    }    
    
    private void configure() {
        addressTextField.setText(_proxy.getListenServer());
        portTextField.setText(Integer.toString(_proxy.getListenPort()));
    }
    
    public void addPlugin(SwingPlugin plugin) {
        if (_plugins == null) {
            _plugins = new ArrayList();
        }
        _plugins.add(plugin);
        _pluginArray = (SwingPlugin[]) _plugins.toArray(_pluginArray);
        mainTabbedPane.add(plugin.getPanel(), plugin.getPluginName());
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        java.awt.GridBagConstraints gridBagConstraints;

        mainTabbedPane = new javax.swing.JTabbedPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        addressTextField = new javax.swing.JTextField();
        portTextField = new javax.swing.JTextField();

        setLayout(new java.awt.GridBagLayout());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(mainTabbedPane, gridBagConstraints);

        jLabel1.setText("Listen Address");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        add(jLabel1, gridBagConstraints);

        jLabel2.setText("Port");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        add(jLabel2, gridBagConstraints);

        addressTextField.setMinimumSize(new java.awt.Dimension(100, 19));
        addressTextField.setPreferredSize(new java.awt.Dimension(125, 19));
        addressTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressTextFieldActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        add(addressTextField, gridBagConstraints);

        portTextField.setMinimumSize(new java.awt.Dimension(40, 19));
        portTextField.setPreferredSize(new java.awt.Dimension(40, 19));
        portTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                portTextFieldActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        add(portTextField, gridBagConstraints);

    }//GEN-END:initComponents

    private void portTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_portTextFieldActionPerformed
        addrChanged();
    }//GEN-LAST:event_portTextFieldActionPerformed

    private void addressTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressTextFieldActionPerformed
        if (addressTextField.getText().equals("")) {
            addressTextField.setText("*");
        }
        addrChanged();
    }//GEN-LAST:event_addressTextFieldActionPerformed

    private void addrChanged() {
        try {
            int port = Integer.parseInt(portTextField.getText());
            if (port > 0 && port <65536) {
                _proxy.setListenAddress(addressTextField.getText(), port);
            } else {
                throw new NumberFormatException("Number out of bounds!");
            }
        } catch (NumberFormatException nfe) {
            portTextField.setText(Integer.toString(_proxy.getListenPort()));
        }
    }
    
    public void newSession(String dir) {
        _proxy.discardSessionData();
        _proxy.initDirectory(dir);
    }
    
    public void openSession(String dir) {
        _proxy.discardSessionData();
        _proxy.loadSessionData(dir);
    }
    
    public void saveSession(String dir) {
        _proxy.initDirectory(dir);
        _proxy.saveSessionData(dir);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTabbedPane mainTabbedPane;
    private javax.swing.JTextField portTextField;
    // End of variables declaration//GEN-END:variables
    
}
