/*
 * Copyright (c) 2002 owasp.org.
 * This file is part of WebScarab.
 * WebScarab is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 * 
 * WebScarab is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * The valid license text for this file can be retrieved with
 * the call:   java -cp owasp.jar org.owasp.webscarab.LICENSE
 * 
 * If you are not able to view the LICENSE that way, which should
 * always be possible within a valid and working WebScarab release,
 * please write to the Free Software Foundation, Inc.,
 * 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 */
/*
 * SpiderTabPane.java
 *
 * Created on 28 June 2002, 13:19
 */

package org.owasp.webscarab.ui.swing.spider;
import org.owasp.webscarab.ui.swing.util.Module;
import org.owasp.webscarab.ui.swing.util.AuditRowBean;
import org.owasp.webscarab.ui.swing.EventRouter;
import java.net.URL;
import javax.swing.tree.TreePath;

/**
 *
 * @author  thp
 */
public class SpiderTabPane extends javax.swing.JPanel implements Module {

    private URLTreeModel _treeModel;
    
    /** Creates new form SpiderTabPane */
    public SpiderTabPane() {
        initComponents();
        _treeModel = new URLTreeModel();
        _mainTree.setModel( _treeModel );
				_mainTree.setRootVisible( false );
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        _headerPane = new javax.swing.JPanel();
        _headerURLTextField = new javax.swing.JTextField();
        _headerStopButton = new javax.swing.JButton();
        _headerStartButton = new javax.swing.JButton();
        _footerPane = new javax.swing.JPanel();
        _footerStatusLabel = new javax.swing.JLabel();
        _footerStatusProgressBar = new javax.swing.JProgressBar();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        _mainTree = new javax.swing.JTree();
        
        setLayout(new java.awt.BorderLayout());
        
        setBorder(new javax.swing.border.MatteBorder(null));
        _headerPane.setLayout(new java.awt.BorderLayout());
        
        _headerPane.setBorder(new javax.swing.border.EtchedBorder());
        _headerURLTextField.setText("http://www.owasp.org");
        _headerURLTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _headerURLTextFieldActionPerformed(evt);
            }
        });
        
        _headerPane.add(_headerURLTextField, java.awt.BorderLayout.CENTER);
        
        _headerStopButton.setText("Stop");
        _headerStopButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _headerStopButtonActionPerformed(evt);
            }
        });
        
        _headerPane.add(_headerStopButton, java.awt.BorderLayout.WEST);
        
        _headerStartButton.setText("Start");
        _headerStartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _headerStartButtonActionPerformed(evt);
            }
        });
        
        _headerPane.add(_headerStartButton, java.awt.BorderLayout.EAST);
        
        add(_headerPane, java.awt.BorderLayout.NORTH);
        
        _footerPane.setLayout(new java.awt.BorderLayout());
        
        _footerPane.setBorder(new javax.swing.border.EtchedBorder());
        _footerStatusLabel.setText("jLabel1");
        _footerPane.add(_footerStatusLabel, java.awt.BorderLayout.CENTER);
        
        _footerStatusProgressBar.setValue(50);
        _footerPane.add(_footerStatusProgressBar, java.awt.BorderLayout.EAST);
        
        jLabel2.setText("jLabel2");
        _footerPane.add(jLabel2, java.awt.BorderLayout.WEST);
        
        add(_footerPane, java.awt.BorderLayout.SOUTH);
        
        jScrollPane1.setViewportView(_mainTree);
        
        add(jScrollPane1, java.awt.BorderLayout.CENTER);
        
    }//GEN-END:initComponents

    private EventRouter _evr = null;
    public void setEventRouter(EventRouter evr){
        _evr = evr;
        if ( null != _evr ){
            _evr.setModule( this, EventRouter.IDX_SPIDER );
        }
    }
    private void _headerStartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__headerStartButtonActionPerformed
        if (_evr != null){
	   invokeURL();
        }
    }//GEN-LAST:event__headerStartButtonActionPerformed

    private void _headerStopButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__headerStopButtonActionPerformed
        if (_evr != null){
            _evr.stopPortal();
        }
    }//GEN-LAST:event__headerStopButtonActionPerformed

    private void _headerURLTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__headerURLTextFieldActionPerformed
        if (_evr != null){
	   invokeURL();
        }
    }//GEN-LAST:event__headerURLTextFieldActionPerformed


    private void invokeURL(){
			try {
			String urlstring = _headerURLTextField.getText();
      _evr.parseAndPush( urlstring );
      _treeModel.setRootURL( new URL( urlstring ) );
			} catch (Exception x) {}
    }
    /**
     * called to set the running/paused status
     */
    public void setState(boolean run) {
    }    

    /**
     * called to set the progress bar
     */
    public void setProgress(int percent) {
    }    

    /**
     * called with a row from the database that needs displaying
     */
    public void setData( AuditRowBean row ) {
			TreePath path = _treeModel.insertURL( row.getTarget() );
			if ( null != path )
				_mainTree.scrollPathToVisible( path );
			_mainTree.repaint();
    }
    
    /**
     * called to set the status text on the bottom line of tab pane
     */
    public void setStatusText(String statusLine) {
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel _headerPane;
    private javax.swing.JTextField _headerURLTextField;
    private javax.swing.JButton _headerStopButton;
    private javax.swing.JButton _headerStartButton;
    private javax.swing.JPanel _footerPane;
    private javax.swing.JLabel _footerStatusLabel;
    private javax.swing.JProgressBar _footerStatusProgressBar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTree _mainTree;
    // End of variables declaration//GEN-END:variables

}
